# syntax = docker/dockerfile:1.2
# not slim because we need github depedencies
FROM root-builder as builder

# Create app directory
WORKDIR /app

# to make use of caching, copy only package files and install dependencies
COPY packages/server/package.json ./packages/server/

COPY node_modules .

ARG NODE_ENV
ENV HTTP_PROXY=http://52.81.203.102:9087
ENV HTTPS_PROXY=http://52.81.203.102:9087
RUN npm config set proxy "http://52.81.203.102:9087" 
RUN npm config set https-proxy "http://52.81.203.102:9087"
RUN npm install --loglevel notice --legacy-peer-deps

COPY . .
RUN npm config rm proxy
RUN npm config rm https-proxy
ENV HTTP_PROXY=
ENV HTTPS_PROXY=
# copy then compile the code

ENV APP_ENV=production

FROM node:16-buster-slim as runner
RUN apt update
RUN apt-get -y install git
WORKDIR /app

COPY --from=builder /app ./

CMD ["scripts/start-server.sh"]
