# syntax = docker/dockerfile:1.2
# not slim because we need github depedencies
FROM root-builder as builder
# FROM 118833645905.dkr.ecr.cn-north-1.amazonaws.com.cn/xrengine-bgy-api:latest_prod as builder

# Create app directory
WORKDIR /app

# to make use of caching, copy only package files and install dependencies
COPY packages/server/package.json ./packages/server/


ARG NODE_ENV
ENV HTTP_PROXY=http://52.81.203.102:9087
ENV HTTPS_PROXY=http://52.81.203.102:9087
RUN npm config set proxy "http://52.81.203.102:9087" 
RUN npm config set https-proxy "http://52.81.203.102:9087"
RUN npm config set noproxy "xr-resources.yee.link,npm.taobao.org,registry.npmmirror.com,*.amazonaws.cn,*.amazonaws.com.cn,mirrors.ustc.edu.cn"
RUN npm install --loglevel notice --legacy-peer-deps

COPY . .
RUN npm config rm proxy
RUN npm config rm https-proxy
ENV HTTP_PROXY=
ENV HTTPS_PROXY=
# copy then compile the code

ENV APP_ENV=production

FROM node:16-buster-slim as runner
RUN printf 'deb http://mirrors.tuna.tsinghua.edu.cn/debian/ buster main non-free contrib \n\
#deb-src http://mirrors.tuna.tsinghua.edu.cn/debian/ buster main non-free contrib \n\
deb http://mirrors.tuna.tsinghua.edu.cn/debian-security buster/updates main \n\
#deb-src http://mirrors.aliyun.com/debian-security buster/updates main \n\
deb http://mirrors.tuna.tsinghua.edu.cn/debian/ buster-updates main non-free contrib \n\
#deb-src http://mirrors.tuna.tsinghua.edu.cn/debian/ buster-updates main non-free contrib \n\
deb http://mirrors.tuna.tsinghua.edu.cn/debian/ buster-backports main non-free contrib ' > /etc/apt/sources.list
RUN apt update
RUN apt-get -y install git
WORKDIR /app

COPY --from=builder /app ./

CMD ["scripts/start-server.sh"]
