# syntax = docker/dockerfile:1.2
# not slim because we need github depedencies
FROM root-builder as builder

# Create app directory
WORKDIR /app

# to make use of caching, copy only package files and install dependencies
COPY packages/instanceserver/package.json ./packages/instanceserver/

COPY node_modules .

ARG NODE_ENV
ENV HTTP_PROXY=http://52.81.203.102:9087
ENV HTTPS_PROXY=http://52.81.203.102:9087
RUN npm config set proxy "http://52.81.203.102:9087" 
RUN npm config set https-proxy "http://52.81.203.102:9087"
RUN npm config set noproxy "xr-resources.yee.link,npm.taobao.org,registry.npm.taobao.org,*.amazonaws.cn,*.amazonaws.com.cn,mirrors.ustc.edu.cn"
RUN npm install --loglevel notice --legacy-peer-deps
RUN npm config rm proxy
RUN npm config rm https-proxy
ENV HTTP_PROXY=
ENV HTTPS_PROXY=
COPY . .

# copy then compile the code

ENV APP_ENV=production

FROM node:16-buster-slim as runner
WORKDIR /app

COPY --from=builder /app ./

CMD ["scripts/start-server.sh"]

