# syntax = docker/dockerfile:1.2
# not slim because we need github depedencies
FROM node:16-buster-slim as builder

RUN apt update
RUN apt-get -y install build-essential meson python3-testresources python3-venv python3-pip git wget
# Create app directory
WORKDIR /app

RUN apt install -y build-essential meson python3-testresources python3-venv python3-pip git

# to make use of caching, copy only package files and install dependencies
COPY package.json .
COPY packages/common/package.json ./packages/common/
COPY packages/engine/package.json ./packages/engine/
COPY packages/hyperflux/package.json ./packages/hyperflux/
COPY packages/matchmaking/package.json ./packages/matchmaking/
COPY packages/projects/package.json ./packages/projects/
COPY packages/server/package.json ./packages/server/
COPY packages/server-core/package.json ./packages/server-core/

RUN npm install --loglevel notice --legacy-peer-deps

COPY . .

# copy then compile the code

ENV APP_ENV=production

FROM node:16-buster-slim as runner
WORKDIR /app

COPY --from=builder /app ./

RUN printf 'deb http://mirrors.tuna.tsinghua.edu.cn/debian/ buster main non-free contrib \n\
#deb-src http://mirrors.tuna.tsinghua.edu.cn/debian/ buster main non-free contrib \n\
deb http://mirrors.tuna.tsinghua.edu.cn/debian-security buster/updates main \n\
#deb-src http://mirrors.aliyun.com/debian-security buster/updates main \n\
deb http://mirrors.tuna.tsinghua.edu.cn/debian/ buster-updates main non-free contrib \n\
#deb-src http://mirrors.tuna.tsinghua.edu.cn/debian/ buster-updates main non-free contrib \n\
deb http://mirrors.tuna.tsinghua.edu.cn/debian/ buster-backports main non-free contrib ' > /etc/apt/sources.list

CMD ["scripts/run-builder.sh"]
