# syntax = docker/dockerfile:1.2
# not slim because we need github depedencies
FROM root-builder as builder

# Create app directory
WORKDIR /app

COPY node_modules .

RUN npm install --loglevel notice --legacy-peer-deps
# copy then compile the code
COPY . .

ENV HTTP_PROXY=http://52.81.203.102:9087
ENV HTTPS_PROXY=http://52.81.203.102:9087

ENV APP_ENV=production

FROM node:16-buster-slim as runner

WORKDIR /app

RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app ./

ENV HTTP_PROXY=
ENV HTTPS_PROXY=

CMD ["scripts/start-testbot.sh"]
