# syntax = docker/dockerfile:1.2
# not slim because we need github depedencies
FROM node:16-buster-slim as root-builder


ENV HTTP_PROXY=http://52.81.203.102:9087
ENV HTTPS_PROXY=http://52.81.203.102:9087
RUN npm config set proxy "http://52.81.203.102:9087" 
RUN npm config set https-proxy "http://52.81.203.102:9087"

RUN apt update
# Create app directory
WORKDIR /app

RUN apt-get -y install build-essential meson python3-testresources python3-venv python3-pip git wget

COPY package.json .
COPY packages/common/package.json ./packages/common/
COPY packages/engine/package.json ./packages/engine/
COPY packages/hyperflux/package.json ./packages/hyperflux/
COPY packages/matchmaking/package.json ./packages/matchmaking/
COPY packages/projects/package.json ./packages/projects/
COPY packages/server-core/package.json ./packages/server-core/
COPY project-package-jsons ./

RUN mkdir /root/.npm/_libvips
RUN wget -O /root/.npm/_libvips/libvips-8.12.2-linux-x64.tar.br https://xr-resources.oss-cn-beijing.aliyuncs.com/Asset/libvips-8.12.2-linux-x64.tar.br

ARG NODE_ENV
RUN npm install --loglevel notice --legacy-peer-deps

ENV HTTP_PROXY=
ENV HTTPS_PROXY=
RUN npm config rm proxy
RUN npm config rm https-proxy
