# syntax = docker/dockerfile:1.2
# not slim because we need github depedencies
FROM node:16-buster-slim as root-builder
# FROM 118833645905.dkr.ecr.cn-north-1.amazonaws.com.cn/xrengine-bgy-root-builder:latest_prod as root-builder

ENV HTTP_PROXY=http://52.81.203.102:9087
ENV HTTPS_PROXY=http://52.81.203.102:9087
ENV NO_PROXY=xr-resources.yee.link,mirrors.ustc.edu.cn,npm.taobao.org,registry.npm.taobao.org,*.amazonaws.cn,*.amazonaws.com.cn,bgy-static-resources.s3.cn-north-1.amazonaws.com.cn,*.s3.cn-north-1.amazonaws.com.cn,s3.cn-north-1.amazonaws.com.cn,*.cn-north-1.amazonaws.com.cn

RUN npm config set proxy "http://52.81.203.102:9087" 
RUN npm config set https-proxy "http://52.81.203.102:9087"

RUN npm config set registry https://registry.npm.taobao.org
RUN npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/
RUN npm config set noproxy "xr-resources.yee.link,mirrors.ustc.edu.cn,registry.npm.taobao.org,*.npm.taobao.org,*.amazonaws.cn,*.amazonaws.com.cn,bgy-static-resources.s3.cn-north-1.amazonaws.com.cn,*.s3.cn-north-1.amazonaws.com.cn,*.cn-north-1.amazonaws.com.cn,s3.cn-north-1.amazonaws.com.cn"

RUN apt update
# Create app directory
WORKDIR /app

RUN apt-get -y install build-essential meson python3-testresources python3-venv python3-pip git wget

COPY package.json .
COPY packages/common/package.json ./packages/common/
COPY packages/engine/package.json ./packages/engine/
COPY packages/hyperflux/package.json ./packages/hyperflux/
COPY packages/matchmaking/package.json ./packages/matchmaking/
COPY packages/projects/package.json ./packages/projects/
COPY packages/server-core/package.json ./packages/server-core/
COPY project-package-jsons ./

ARG NODE_ENV
RUN npm install --loglevel notice --legacy-peer-deps
